# Generated by Django 5.1.6 on 2025-03-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
