# Generated by Django 5.1.3 on 2025-06-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courses_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='courses/photos'),
        ),
    ]
